#!/usr/bin/env bash

# Start the process in the background
./4-to_infinity_and_beyond &

# Get the process ID (PID)
PID=$!

# Wait for a few seconds
sleep 5

# Stop the process using kill
kill "$PID"
